name: my first workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome message
          run: echo "Welcome to lagos"

        - name: List file
          run: ls
        
        - name: Read readme file
          run: cat README.md
        

